// Art module: effects. See docs/ART_GUIDE.md for the sprite contract.
//
// Particles, weather, emotes and markers. Index 1 is always the darkest
// colour of an effect's palette (an outline where the effect has one).

const O = '#181010';

// ---------------------------------------------------------------- helpers

function grid(art) {
  const rows = art
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);
  const w = rows[0].length;
  for (const r of rows) if (r.length !== w) throw new Error(`effects: ragged art row "${r}" (${r.length} vs ${w})`);
  return rows.map((r) => [...r].map((c) => (c === '.' ? 0 : c.charCodeAt(0) - 48)));
}

function draw(g, x0, y0, art) {
  grid(art).forEach((row, y) => row.forEach((v, x) => v && g.px(x0 + x, y0 + y, v)));
}

const N4 = [[1, 0], [-1, 0], [0, 1], [0, -1]];
const N8 = [...N4, [1, 1], [1, -1], [-1, 1], [-1, -1]];

/** Outline every transparent pixel touching a colour > 1 with index 1. */
function outline(g, diag = false) {
  const src = g.data.slice();
  const nb = diag ? N8 : N4;
  for (let y = 0; y < g.h; y++)
    for (let x = 0; x < g.w; x++) {
      if (src[y * g.w + x]) continue;
      for (const [dx, dy] of nb) {
        const xx = x + dx, yy = y + dy;
        if (xx < 0 || yy < 0 || xx >= g.w || yy >= g.h) continue;
        if (src[yy * g.w + xx] > 1) {
          g.px(x, y, 1);
          break;
        }
      }
    }
}

/** Plain ASCII sprite (no automatic outline). */
function art(A, name, pal, a) {
  const gr = grid(a);
  return A.paint(name, pal, gr[0].length, gr.length, (g) => draw(g, 0, 0, a));
}

/** ASCII sprite whose colours > 1 get an automatic index-1 outline. */
function outlined(A, name, pal, a, diag = false) {
  const gr = grid(a);
  return A.paint(name, pal, gr[0].length, gr.length, (g) => {
    draw(g, 0, 0, a);
    outline(g, diag);
  });
}

/** Round puff: light body, shaded lower-right crescent. */
function puff(g, cx, cy, r, light = 3, shade = 2) {
  for (let y = -r; y <= r; y++)
    for (let x = -r; x <= r; x++) {
      const d = x * x + y * y;
      if (d > r * r + r * 0.8) continue;
      const sh = (x + 0.6) * (x + 0.6) + (y + 0.6) * (y + 0.6) > (r - 0.4) * (r - 0.4) && x + y > 0;
      g.px(cx + x, cy + y, sh ? shade : light);
    }
}

// ---------------------------------------------------------------- weather

function weather(A) {
  A.pal('fx_rain', ['#5078b8', '#98c0f0', '#e8f8f8']);
  art(A, 'fx_rain', 'fx_rain', `
    ..1
    ..1
    .1.
    .2.
    .2.
    2..
    3..
    3..
  `);
  art(A, 'fx_splash_0', 'fx_rain', `
    ........
    ..3..3..
    ...22...
    ..1111..
  `);
  art(A, 'fx_splash_1', 'fx_rain', `
    3......3
    .2....2.
    ........
    .1....1.
  `);

  A.pal('fx_snow', ['#a0b0d0', '#f8f8f8']);
  art(A, 'fx_snow_0', 'fx_snow', `
    .2.
    222
    .1.
  `);
  art(A, 'fx_snow_1', 'fx_snow', `
    .22.
    2222
    2221
    .11.
  `);

  A.pal('fx_petal', ['#c05078', '#f098b8', '#f8d8e8']);
  art(A, 'fx_petal', 'fx_petal', `
    .33.
    3322
    .221
    ..1.
  `);

  A.pal('fx_leaf', ['#904018', '#d87020', '#f8b040']);
  art(A, 'fx_leaf', 'fx_leaf', `
    ...33
    ..332
    .3322
    .222.
    1....
  `);
}

// ---------------------------------------------------------------- work particles

function particles(A) {
  // dust puff: grows, then breaks up and fades
  A.pal('fx_dust', ['#806848', '#c0a078', '#e8d8b8']);
  A.paint('fx_dust_0', 'fx_dust', 16, 16, (g) => {
    puff(g, 6, 12, 2);
    puff(g, 10, 12, 2);
    puff(g, 8, 11, 2);
    outline(g);
  });
  A.paint('fx_dust_1', 'fx_dust', 16, 16, (g) => {
    puff(g, 4, 11, 2);
    puff(g, 12, 11, 2);
    puff(g, 8, 8, 3);
    puff(g, 6, 11, 2);
    puff(g, 10, 11, 3);
    outline(g);
  });
  A.paint('fx_dust_2', 'fx_dust', 16, 16, (g) => {
    puff(g, 3, 9, 1);
    puff(g, 13, 9, 1);
    puff(g, 8, 4, 1);
    puff(g, 5, 5, 1);
    puff(g, 11, 6, 1);
    g.px(2, 13, 3); g.px(14, 12, 3); g.px(8, 1, 3);
    outline(g);
  });

  // watering: drops fall, hit the soil, splash outward
  A.pal('fx_water', ['#2860a8', '#58a0e8', '#a8d8f8', '#f8f8f8']);
  art(A, 'fx_water_0', 'fx_water', `
    ................
    ....4.....4.....
    ....3.....3.....
    ....2..4..2.....
    .......3......4.
    .......2......3.
    ..4...........2.
    ..3.....4.......
    ..2.....3.......
    ........2...4...
    ............3...
    .....4......2...
    .....3..........
    .....2..........
    ................
    ................
  `);
  art(A, 'fx_water_1', 'fx_water', `
    ................
    ................
    ................
    ................
    .......4........
    .......3........
    ..4....2....4...
    ..3.........3...
    ..2...4..4..2...
    ....4..44..4....
    .4..3.2332.3..4.
    ..3.2233322.3...
    ...223333332....
    ....11222211....
    ................
    ................
  `);
  art(A, 'fx_water_2', 'fx_water', `
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    .4............4.
    ..3...4..4...3..
    ......3..3......
    4..............4
    .3............3.
    ...2233333322...
    ..233344443332..
    ...1122222211...
    ................
  `);

  A.pal('fx_grass', ['#185018', '#48a030', '#90d050']);
  art(A, 'fx_grass_0', 'fx_grass', `
    ................
    ................
    ................
    ................
    ................
    .......3........
    ....3..2..3.....
    ...32.....23....
    ....1..3...1....
    ......32........
    ..3...1....33...
    ..21.......21...
    ......3.3.......
    .....21.12......
    ................
    ................
  `);
  art(A, 'fx_grass_1', 'fx_grass', `
    ................
    ......3.........
    ......21.....3..
    .3...........2..
    .21..........1..
    ................
    ..........3.....
    3.........21....
    21..............
    ...............3
    ..............21
    ..3.............
    ..21.....3......
    .........21.....
    ....3.......3...
    ....21......21..
  `);

  A.pal('fx_chip', ['#383840', '#787880', '#b8b8c0', '#e8e8f0']);
  A.paint('fx_chip_0', 'fx_chip', 16, 16, (g) => {
    draw(g, 0, 0, `
      ................
      ................
      ................
      ................
      ................
      ................
      .......4........
      ....43.33..43...
      ....32.....32...
      ................
      ......43.43.....
      ......3..32.....
      ................
      ................
      ................
      ................
    `);
    outline(g);
  });
  A.paint('fx_chip_1', 'fx_chip', 16, 16, (g) => {
    draw(g, 0, 0, `
      ................
      .......4........
      ................
      ..43.......43...
      ..32.......32...
      ................
      ................
      ................
      .4............4.
      ................
      ................
      ...43......43...
      ...3........32..
      ................
      ................
      ................
    `);
    outline(g);
  });

  A.pal('fx_wood', ['#482810', '#986030', '#d8a860']);
  A.paint('fx_wood_0', 'fx_wood', 16, 16, (g) => {
    draw(g, 0, 0, `
      ................
      ................
      ................
      ................
      ................
      ................
      ........3.......
      ....33..32..33..
      .....2.......2..
      ................
      ......33..3.....
      ...........2....
      ................
      ................
      ................
      ................
    `);
    outline(g);
  });
  A.paint('fx_wood_1', 'fx_wood', 16, 16, (g) => {
    draw(g, 0, 0, `
      ................
      ........3.......
      ........2.......
      ..33.........33.
      ...2..........2.
      ................
      ................
      ................
      .3............3.
      .2............2.
      ................
      ...33.......33..
      ................
      ................
      ................
      ................
    `);
    outline(g);
  });
}

// ---------------------------------------------------------------- emotes

function emotes(A) {
  A.pal('fx_sparkle', ['#e09818', '#f8e070', '#f8f8e8']);
  art(A, 'fx_sparkle_0', 'fx_sparkle', `
    ........
    ........
    ...2....
    ..232...
    ...2....
    ........
    ........
    ........
  `);
  art(A, 'fx_sparkle_1', 'fx_sparkle', `
    ...1....
    ...2....
    ..232...
    1233321.
    ..232...
    ...2....
    ...1....
    ........
  `);
  art(A, 'fx_sparkle_2', 'fx_sparkle', `
    ........
    .1...1..
    ..2.2...
    ...3....
    ..2.2...
    .1...1..
    ........
    ........
  `);

  A.pal('fx_heart', [O, '#b81838', '#f04868', '#f8c0c8']);
  art(A, 'fx_heart', 'fx_heart', `
    .11.11..
    1431331.
    1433321.
    1333321.
    .13321..
    ..121...
    ...1....
    ........
  `);

  A.pal('fx_note', [O, '#3858c8', '#88b0f8']);
  A.paint('fx_note', 'fx_note', 8, 8, (g) => {
    draw(g, 0, 0, `
      ........
      ....33..
      ....2.3.
      ....2..3
      ....2...
      ..332...
      ..222...
      ........
    `);
    outline(g);
  });

  // big Z in deep blue, a smaller lighter z drifting up-right
  A.pal('fx_zzz', ['#283878', '#6880d8']);
  art(A, 'fx_zzz', 'fx_zzz', `
    .....222
    .......2
    ......2.
    .....222
    1111....
    ..1.....
    .1......
    1111....
  `);

  A.pal('fx_emote', [O, '#e0a010', '#f8e858']);
  outlined(A, 'fx_exclaim', 'fx_emote', `
    ........
    ...33...
    ...33...
    ...33...
    ...22...
    ........
    ...3....
    ........
  `);
  outlined(A, 'fx_question', 'fx_emote', `
    ........
    ..333...
    .3...3..
    ....3...
    ...2....
    ........
    ...3....
    ........
  `);

  A.pal('fx_sweat', ['#2050a8', '#58a0f0', '#b0e0f8', '#f8f8f8']);
  A.paint('fx_sweat', 'fx_sweat', 8, 8, (g) => {
    draw(g, 0, 0, `
      ........
      ....2...
      ...32...
      ..3422..
      ..3322..
      ..3222..
      ...22...
      ........
    `);
    outline(g);
  });

  A.pal('fx_bobber', [O, '#b82020', '#f85840', '#f8f8e8', '#98c8f0']);
  art(A, 'fx_bobber_0', 'fx_bobber', `
    ...1....
    ...1....
    ..1221..
    .132221.
    .144441.
    ..1441..
    5..11..5
    ........
  `);
  art(A, 'fx_bobber_1', 'fx_bobber', `
    ........
    ...1....
    ...1....
    ..1221..
    .132221.
    .144441.
    55.11.55
    ........
  `);

  A.pal('fx_ripple', ['#5890d0', '#a8d8f8', '#f8f8f8']);
  // ring spreads outward and breaks up; lit rim on top, darker rim below
  art(A, 'fx_ripple_0', 'fx_ripple', `
    ................
    ................
    ................
    ......3333......
    .....3....3.....
    ......2222......
    ................
    ................
  `);
  art(A, 'fx_ripple_1', 'fx_ripple', `
    ................
    ................
    .....333333.....
    ...33......33...
    ...2........2...
    ....22....22....
    ......2222......
    ................
  `);
  art(A, 'fx_ripple_2', 'fx_ripple', `
    ................
    .....22..22.....
    ..2..........2..
    .2............2.
    .1............1.
    ..1..........1..
    .....11..11.....
    ................
  `);
}

// ---------------------------------------------------------------- markers & wisps

function markers(A) {
  A.pal('shadow', ['#182018']);
  art(A, 'fx_shadow', 'shadow', `
    ..11111111..
    .1111111111.
    111111111111
    .1111111111.
    ..11111111..
  `);

  A.pal('fx_cursor', [O, '#f8f8e8']);
  A.paint('fx_cursor', 'fx_cursor', 16, 16, (g) => {
    const corner = (fx, fy) => {
      for (let k = 0; k < 5; k++) {
        g.px(fx ? 14 - k : 1 + k, fy ? 14 : 1, 2);
        g.px(fx ? 14 : 1, fy ? 14 - k : 1 + k, 2);
      }
    };
    corner(0, 0);
    corner(1, 0);
    corner(0, 1);
    corner(1, 1);
    outline(g, true);
  });

  // steam: a curl forms, rises into an S, then breaks apart
  A.pal('fx_steam', ['#a8b0c0', '#e0e8f0', '#f8f8f8']);
  art(A, 'fx_steam_0', 'fx_steam', `
    ........
    ........
    ........
    ........
    ....3...
    ...33...
    ...22...
    ....1...
  `);
  art(A, 'fx_steam_1', 'fx_steam', `
    ........
    ...3....
    ..332...
    ..3.....
    ...33...
    ....32..
    ....2...
    ........
  `);
  art(A, 'fx_steam_2', 'fx_steam', `
    ..3..3..
    .32.332.
    .2....1.
    ........
    ...1....
    ........
    ........
    ........
  `);

  // smoke: a small puff swells and drifts up, then thins out
  A.pal('fx_smoke', ['#484850', '#808088', '#b8b8c0']);
  A.paint('fx_smoke_0', 'fx_smoke', 8, 8, (g) => {
    puff(g, 4, 5, 1);
    g.px(3, 6, 3);
    outline(g);
  });
  A.paint('fx_smoke_1', 'fx_smoke', 8, 8, (g) => {
    puff(g, 3, 4, 2);
    puff(g, 5, 3, 1);
    outline(g);
  });
  A.paint('fx_smoke_2', 'fx_smoke', 8, 8, (g) => {
    puff(g, 2, 2, 1);
    puff(g, 5, 1, 1);
    g.px(4, 4, 3);
    g.px(6, 4, 2);
    g.px(1, 5, 2);
    outline(g);
  });
}

export function register(A) {
  weather(A);
  particles(A);
  emotes(A);
  markers(A);
}
